### ISSUE TITLE
Enhancement: Slope Selector Plots Display

### ISSUE THREAD

**Issue by js3110** [pharmaverse/aNCA#23]
**Description**

Currently slope selector plots are ugly. Aim to show one plot per page. If user wants >1 plot per page plots should be in grid format. 

**To do**

- [ ] One slope plot per page
- [ ] Option for Multiple plots on page in grid format
- [ ] Improve axis labels, titles and font sizes etc so plots are easy to read and no overlapping sections or unclear titles,

**Comment by js3110** [comment]
@Gero1999 @m-kolomanski 
hi guys I have been trying to work on this issue for the past 3 days and have not been able to get anywhere. I have tried lots of different methods to get the plots to look better but I can't seem to get there. So I am asking for help!

The first issue is that the title and subtitle are overlapping currently. I tried to fix this using [this](https://stackoverflow.com/questions/64605828/create-a-ggplotly-object-with-a-subtitle) method, but it just ended up cutting off both of the titles. I tried some other things too just rearranging stuff but to no avail.

The other problem is the layout- at the moment if you want to show more plots on the page it just adds them underneath and the user has to scroll, which is pointless. I would like it to be similar to in phoenix where if you select for example 4 plots per page, the plots show up in a 2x2 grid format- so they become smaller in order to fit on the page. I tried this using an updating fluidRow that switched based on the user input however the plots just overlapped and didn't change size no matter how many things I changed to try and fix it.

So I am giving up and asking if either of you is able to help. If so then good luck, and just assign yourself to the issue :)

**Comment by m-kolomanski** [comment]
Hey @js3110 @Gero1999,

I can get on that task, but I will not have the time before Thursday. If the task is available on Thursday, I can pick it up.

**Comment by m-kolomanski** [comment]
Hey @js3110,

at this moment, all functionalities of slope selector are migrated to separate module and should be working as expected - please do check if that is also the case for you. That said, I think there is a lot of room for improvements, not only UX-wise, but also in terms of the code itself. Here are changes that I would suggest:

1. We could migrate the plot itself to separate module to further break the feature into components - this way each plot would be separate module and would handle the clicks, returning just the selection data to parent module. Then the actual implementation of the plots are decoupled from the rest of the functionality, meaning editing them will be easier.
2. For the selection table, I would suggest giving [reactable](https://glin.github.io/reactable/) with [reactable.extras](https://appsilon.github.io/reactable.extras/articles/tutorial/custom-inputs.html) a go for two reasons - `reactable` is more modern package compared to `DT` and is generally nowadays recommended, and with `reactable.extras` it supports things like text and pick-list inputs, so that would simplify the process of displaying the table with widgets, as well as gathering user inputs a lot.
3. Throw the function definitions outside of server function. We could also think about which parts of the code can be migrated to the logic functions in `R` folder - this will mean we will be able to write unit tests for them easily and make sure they are more robust.
4. We should address the warnings coming from plotly. On that note, using plotly is 100% fine, but there are also alternatives we could go for that are a bit simpler and more performant in my experience, like [ggiraph](http://davidgohel.github.io/ggiraph/). I am myself not sure about that yet, depends if we want all the functionalities provided by plotly (zooming, saving etc) and it is also good to keep consistent across the whole package.
5. Those are all technical changes, but of course there are UX improvements that have already been discussed like:
    - making the plot prettier (fixing overlapping labels etc)
    - improving plot layout (better page split, implementing grid layout etc)
    - fixing/adding help widget
    - other minor improvements

Please let me know what you think about all this and what you would like to add and change in this module, we will then add those points to definition of done for the draft PR #98 and go from there.

**Comment by js3110** [comment]
hi @m-kolomanski !

I have had a look at the branch to test it out. The plots look good however I am unable to click and select the points and when I hover over them with the cursor most of the time nothing shows up.

in regards to your points: 1-3 sound good to me, definitely worth implementing to improve the functionalities. 4- Maybe its worth having a go as I don't know that plotly is required for this section, as it is used in the outputs section that is where the zoom and download features are more important, whereas in this section the priority is just viewing and selecting the slopes so we could see if ggiraph works better in that respect?
And yes all the UX improvements I think I have already mentioned and definitely need implementing as currently the plots do not look great lol

Let me know if there is anything I can do to help- I spent yesterday reading everything about modules so I feel a bit more ready to give it a go!

**Comment by js3110** [comment]
@m-kolomanski also worth noting that issue #36 is also related to slope selectors, to keep in mind when making changes.

**Comment by js3110** [comment]
@m-kolomanski I have committed the work I was able to do so far to switch from DT to reactable. The table and widgets work fine, however at the moment the inputs are not being saved and updating manual_slopes() which means they are then not transferred to the nca. I could not figure out a way to do this. I know it must involve using the input$columnid from reactable.extras but I couldn't figure out the exact logistics. Maybe you will have better luck!
Its worth noting that the table does correctly update if the row is added via plotly select.
